### ISSUE TITLE
Create Julia, Fount, BDO, and Pref clients in Rust

### ISSUE THREAD

**Issue by zach-planet-nine** [planet-nine-app/juliaswitch#9]
The "backend" of the app is written in Rust, and interacts with [allyabase](https://www.github.com/planet-nine-app/allyabase) services. Specifically Julia, Fount, BDO, and Pref. We need clients in Rust for these services to use them with Tauri

**Comment by zach-freyja** [comment]
Actually Julia and Fount are the only ones needed, and they are donezo
